os: osx
language: cpp

branches:
  only:
  - master

before_script:
  - brew unlink boost
  - brew install boost
  - brew install gsl
  - pip install --user cpp-coveralls
  
notifications:
   email:
     recipients:
       - mohcine@chraibi.de
     on_success: change
     on_failure: always

  
script:
  - make        
  - ./overlap testcases.txt 1

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'