os: osx
language: cpp

branches:
  only:
  - master

before_script:
  - sudo brew update
  - sudo brew unlink boost
  - sudo brew install boost
  - sudo brew install gsl
  - sudo pip install pyyaml
  - sudo brew unlink pyenv
  - sudo brew install pyenv
  - eval "$(pyenv init -)"
  - pyenv install 2.7.6
  - pyenv global 2.7.6
  - pyenv rehash
  - sudo pip install cpp-coveralls
  - pyenv rehash
  
notifications:
   email:
     recipients:
       - mohcine@chraibi.de
     on_success: change
     on_failure: always

  
script:
  - make        
  - ./overlap testcases.txt 1

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'