language: cpp
compiler:
- g++

branches:
  only:
  - master

before_script:
  - sudo apt-add-repository ppa:timklingt/ppa
  - sudo apt-get update
  - sudo apt-get install libboost1.55-all-dev

notifications:
   email:
     recipients:
       - mohcine@chraibi.de
     on_success: change
     on_failure: always

  
script:
  - make        
  - ./overlap testcases.txt 1
