os: osx
language: cpp

branches:
  only:
  - master

before_script:
  - sudo brew update
  - sudo brew unlink boost
  - sudo brew install boost
  - sudo brew install gsl
  
notifications:
   email:
     recipients:
       - mohcine@chraibi.de
     on_success: change
     on_failure: always

  
script:
  - make        
  - ./overlap testcases.txt 1

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"